### ISSUE TITLE
ipython-kernel fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [gibiansky/IHaskell#1307]
```
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Message/UUID.hs:6:1: warning: [-Wunused-imports]
ipython-kernel            >     The import of ‘Control.Applicative’ is redundant
ipython-kernel            >       except perhaps to import instances from ‘Control.Applicative’
ipython-kernel            >     To import instances alone, use: import Control.Applicative()
ipython-kernel            >   |
ipython-kernel            > 6 | import           Control.Applicative ((<$>))
ipython-kernel            >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > [2 of 6] Compiling IHaskell.IPython.Types
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:570:45: error:
ipython-kernel            >     • Couldn't match type ‘Text’ with ‘Key’
ipython-kernel            >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
ipython-kernel            >         Actual: [(Text, Value)]
ipython-kernel            >     • In the first argument of ‘object’, namely
ipython-kernel            >         ‘(map displayDataToJson o)’
ipython-kernel            >       In the second argument of ‘(.=)’, namely
ipython-kernel            >         ‘object (map displayDataToJson o)’
ipython-kernel            >       In the expression: "data" .= object (map displayDataToJson o)
ipython-kernel            >     |
ipython-kernel            > 570 |                         , "data" .= object (map displayDataToJson o)
ipython-kernel            >     |                                             ^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:590:27: error:
ipython-kernel            >     • Couldn't match type ‘Text’ with ‘Key’
ipython-kernel            >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
ipython-kernel            >         Actual: [(Text, Value)]
ipython-kernel            >     • In the first argument of ‘object’, namely
ipython-kernel            >         ‘(map displayDataToJson datas)’
ipython-kernel            >       In the second argument of ‘(.=)’, namely
ipython-kernel            >         ‘object (map displayDataToJson datas)’
ipython-kernel            >       In the expression: "data" .= object (map displayDataToJson datas)
ipython-kernel            >     |
ipython-kernel            > 590 |       , "data" .= object (map displayDataToJson datas)
ipython-kernel            >     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:598:27: error:
ipython-kernel            >     • Couldn't match type ‘Text’ with ‘Key’
ipython-kernel            >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
ipython-kernel            >         Actual: [(Text, Value)]
ipython-kernel            >     • In the first argument of ‘object’, namely
ipython-kernel            >         ‘(map displayDataToJson datas)’
ipython-kernel            >       In the second argument of ‘(.=)’, namely
ipython-kernel            >         ‘object (map displayDataToJson datas)’
ipython-kernel            >       In the expression: "data" .= object (map displayDataToJson datas)
ipython-kernel            >     |
ipython-kernel            > 598 |       , "data" .= object (map displayDataToJson datas)
ipython-kernel            >     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:623:27: error:
ipython-kernel            >     • Couldn't match type ‘Text’ with ‘Key’
ipython-kernel            >       Expected: [aeson-2.0.2.0:Data.Aeson.Types.Internal.Pair]
ipython-kernel            >         Actual: [(Text, Value)]
ipython-kernel            >     • In the first argument of ‘object’, namely
ipython-kernel            >         ‘(map displayDataToJson . inspectData $ i)’
ipython-kernel            >       In the second argument of ‘(.=)’, namely
ipython-kernel            >         ‘object (map displayDataToJson . inspectData $ i)’
ipython-kernel            >       In the expression:
ipython-kernel            >         "data" .= object (map displayDataToJson . inspectData $ i)
ipython-kernel            >     |
ipython-kernel            > 623 |       , "data" .= object (map displayDataToJson . inspectData $ i)
ipython-kernel            >     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:842:5: error:
ipython-kernel            >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
ipython-kernel            >     • In the first argument of ‘(.=)’, namely ‘pack (show MimeJson)’
ipython-kernel            >       In the expression:
ipython-kernel            >         pack (show MimeJson)
ipython-kernel            >           .=
ipython-kernel            >             fromMaybe
ipython-kernel            >               (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >       In an equation for ‘displayDataToJson’:
ipython-kernel            >           displayDataToJson (DisplayData MimeJson dataStr)
ipython-kernel            >             = pack (show MimeJson)
ipython-kernel            >                 .=
ipython-kernel            >                   fromMaybe
ipython-kernel            >                     (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |
ipython-kernel            > 842 |     pack (show MimeJson) .= fromMaybe (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |     ^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:844:5: error:
ipython-kernel            >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
ipython-kernel            >     • In the first argument of ‘(.=)’, namely
ipython-kernel            >         ‘pack (show MimeVegalite)’
ipython-kernel            >       In the expression:
ipython-kernel            >         pack (show MimeVegalite)
ipython-kernel            >           .=
ipython-kernel            >             fromMaybe
ipython-kernel            >               (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >       In an equation for ‘displayDataToJson’:
ipython-kernel            >           displayDataToJson (DisplayData MimeVegalite dataStr)
ipython-kernel            >             = pack (show MimeVegalite)
ipython-kernel            >                 .=
ipython-kernel            >                   fromMaybe
ipython-kernel            >                     (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |
ipython-kernel            > 844 |     pack (show MimeVegalite) .= fromMaybe (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |     ^^^^^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:846:5: error:
ipython-kernel            >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
ipython-kernel            >     • In the first argument of ‘(.=)’, namely ‘pack (show MimeVega)’
ipython-kernel            >       In the expression:
ipython-kernel            >         pack (show MimeVega)
ipython-kernel            >           .=
ipython-kernel            >             fromMaybe
ipython-kernel            >               (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >       In an equation for ‘displayDataToJson’:
ipython-kernel            >           displayDataToJson (DisplayData MimeVega dataStr)
ipython-kernel            >             = pack (show MimeVega)
ipython-kernel            >                 .=
ipython-kernel            >                   fromMaybe
ipython-kernel            >                     (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |
ipython-kernel            > 846 |     pack (show MimeVega) .= fromMaybe (String "") (decodeStrict (Text.encodeUtf8 dataStr) :: Maybe Value)
ipython-kernel            >     |     ^^^^^^^^^^^^^^^^^^^^
ipython-kernel            > 
ipython-kernel            > /tmp/stack-e591e1400205e227/ipython-kernel-0.10.2.1/src/IHaskell/IPython/Types.hs:848:3: error:
ipython-kernel            >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
ipython-kernel            >     • In the first argument of ‘(.=)’, namely ‘pack (show mimeType)’
ipython-kernel            >       In the expression: pack (show mimeType) .= String dataStr
ipython-kernel            >       In an equation for ‘displayDataToJson’:
ipython-kernel            >           displayDataToJson (DisplayData mimeType dataStr)
ipython-kernel            >             = pack (show mimeType) .= String dataStr
ipython-kernel            >     |
ipython-kernel            > 848 |   pack (show mimeType) .= String dataStr
ipython-kernel            >     |   ^^^^^^^^^^^^^^^^^^^^
```

**Comment by vaibhavsagar** [comment]
I worked in this in https://github.com/gibiansky/IHaskell/pull/1297, just need to make new releases.

**Comment by vaibhavsagar** [comment]
Uploaded https://hackage.haskell.org/package/ipython-kernel-0.10.2.2 and https://hackage.haskell.org/package/ihaskell-0.10.2.2.
