### PR TITLE
Work with GHC 8.2

### PR DESCRIPTION
**Pull request by vaibhavsagar**
I'd like to support GHC 8.2 by the time the Stackage LTS package set including it is released. I've updated the package bounds and now I'm running into a GHC API change between <=8.0 and 8.2 where `extraPkgConfs` seems to have been removed and the order of the list it expects has reversed.

To check the current progress, run `nix-build release821.nix`.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Ready for testing! `nix-build release821.nix` should create a working notebook environment!

**Comment by vaibhavsagar** [comment]
I am confused by the test failures and wondering what I changed to cause them.

**Comment by vaibhavsagar** [comment]
I was hoping that upgrading to a new enough resolver would make the problem go away, but I no longer think it will and there's an issue in the codebase that needs to be addressed. I've added a small `failure.hs` that demonstrates the failure on GHC 8.2:

```
$ stack ghci failure.hs
*Main> eval "1 + 1"
*** Exception: Not in scope: ‘IHaskell.Display.displayFromChanEncoded’
No module named ‘IHaskell.Display’ is imported.
```

**Comment by vaibhavsagar** [comment]
The issue appears to be that packages in GHC 8.0 and below are named e.g `ihaskell-1.2.3.4` but in 8.2 they're just `ihaskell`. I'm getting a different error now, so I'll call that progress :tada:

**Comment by vaibhavsagar** [comment]
:tada: :fireworks: :champagne:

**Comment by vaibhavsagar** [comment]
I'm going to split out `release821.nix` and the newer `stack.yaml` into a separate PR, and try to figure out how to test both 8.0 and 8.2 as part of the CI process.
