### ISSUE TITLE
Not in scope/couldn't match type errors on installing

### ISSUE THREAD

**Issue by vinit-ivar** [gibiansky/IHaskell#397]
First off, background - IPython is version 2.2.0, GHCi is version 7.6.3, and Cabal is version 1.22.0.1. libzmq, happy, cpphs and virtualenv all exist as well (the OS is Linux Mint).

Next: installing IHaskell from Cabal gives me this:

```
src/IHaskell/Eval/Util.hs:233:33:
    Couldn't match type `UniqFM.UniqFM TyVar' with `[Var.Var]'
    Expected type: [Var.Var]
      Actual type: VarSet.TyVarSet
    In the first argument of `mkVarSet', namely `tpl_tvs'
    In the expression: mkVarSet tpl_tvs
    In an equation for `tpl_tv_set': tpl_tv_set = mkVarSet tpl_tvs
Failed to install ihaskell-0.5.0.0
cabal: Error: some packages failed to install:
ihaskell-0.5.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

whilst cloning the GitHub repository and running ./build.sh gives me this:

```
[ 3 of 18] Compiling IHaskell.Eval.Util ( src/IHaskell/Eval/Util.hs, dist/build/IHaskell/Eval/Util.o )

src/IHaskell/Eval/Util.hs:92:37:
    Not in scope: `gopt'
    Perhaps you meant one of these:
      `wopt' (imported from DynFlags), `xopt' (imported from DynFlags),
      `dopt' (imported from GHC)

src/IHaskell/Eval/Util.hs:94:37:
    Not in scope: `gopt'
    Perhaps you meant one of these:
      `wopt' (imported from DynFlags), `xopt' (imported from DynFlags),
      `dopt' (imported from GHC)

src/IHaskell/Eval/Util.hs:116:18:
    Not in scope: data constructor `Opt_PrintExplicitKinds'
    Perhaps you meant `Opt_PrintExplicitForalls' (imported from GHC)
cabal: Error: some packages failed to install:
ihaskell-0.5.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

Any suggestions? I tried changing some stuff around, but I probably did an awful job because it didn't work.

**Comment by aavogt** [comment]
The easiest thing to do is probably to use ghc 7.8.

**Comment by gibiansky** [comment]
Indeed, the easiest thing to do is to switch to GHC 7.8. That said I've opened #398 and #399 so that we do eventually get this fixed.

**Comment by gibiansky** [comment]
Should not compile on 7.6.3. Note that some features are disabled then.

**Comment by pmagwene** [comment]
It would be nice if the requirement for GHC 7.8 was actually documented in the installation instructions (currently they suggest that 7.6.3 should work).  

I ran into the same problem and because this issue is closed it didn't come up when I searched for similar reports.

**Comment by gibiansky** [comment]
It should compile on 7.6.3! (Apologies for the confusion -- just noticed that the last comment I made here said 'should not compile' instead of 'should *now* compile'.) What is breaking for you? (Note that only github master supports 7.6.3, probably not the hackage ihaskell)

**Comment by pmagwene** [comment]
I'm getting exactly the same message as the original poster, but I was indeed using the hackage ihaskell.  I'll give it another shot with github master.
