### ISSUE TITLE
Compilation failure with FlagSpec

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#380]
Current `master` head does not compile on GHC 7.8.4:

```
src/IHaskell/Eval/Util.hs:81:17:
    Not in scope: type constructor or class ‘FlagSpec’

src/IHaskell/Eval/Util.hs:84:17:
    Not in scope: type constructor or class ‘FlagSpec’
```

**Comment by gibiansky** [comment]
@bgamari This is due to the `:set` PR. How does one fix this (where is `FlagSpec` from)?

**Comment by gibiansky** [comment]
Fixed this by removing the type signatures. Not optimal but works.

**Comment by bgamari** [comment]
@gibiansky This is rather odd; `FlagSpec`should be exported from `DynFlags` on 7.8.

**Comment by bgamari** [comment]
Ahh, never mind; it's defined but not exported. Removing the type signatures may in fact be the least bad option.
